### ISSUE TITLE
add default config.yml & services.yml to skeleton

### ISSUE THREAD

**Issue by fritzmg** [contao/managed-edition#42]
I think it would make sense if the skeleton of the Contao Managed Edition also provides the following files:
```yml
# config/config.yml
imports:
    - { resource: services.yml }
``` 
```yml
# config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Resources,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
Since the Contao Managed edition already has the appropriate autoloading configuration in its `composer.json` for the `App\` namespace, this would allow every user to quickly write hooks & callbacks, especially now that we have support for annotations, by simply creating _one_ file, without having to do any additional configuration.

I am not sure if the `config.yml` is actually needed in Contao 4.8+ (in Symfony Flex, all the config files in `/config` are loaded automatically; may be we can even provide a default `routes.yml` for annotated routes?).
